FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .
RUN go build -o /bin/messages-projector ./cmd/projector

FROM alpine:3.22
RUN apk add --no-cache ca-certificates
COPY --from=builder /bin/messages-projector /bin/messages-projector
ENTRYPOINT ["/bin/messages-projector"]
